name: 'branch'
description: 'Makes Backlog related branch information available to other actions in your workflow.'
inputs:
  api_token:
    description: 'Your Snap account API token'
    required: true
  debug:
    description: 'If debug logging should be enabled'
    required: false
outputs:
  ignored:
    description: 'If the branch should be ignored'
  matched:
    description: 'If the branch name matched the required format'
  id:
    description: 'The ID of the entity type to which this branch is associated'
  name:
    description: 'The branch name'
  type:
    description: 'The type of branch (task, effort or project)'
runs:
  using: 'node12'
  main: 'dist/index.js'
