name: 'env'
description: 'Makes Snap related information available to other actions via outputs.'
inputs:
  api_token:
    description: 'Your Snap account API token'
    required: true
outputs:
  branch_name:
    description: 'The branch name'
  branch_type:
    description: 'The type of branch (task, effort or project)'
  branch_is_ignored:
    description: 'If the branch should be ignored'
  branch_task_id:
    description: 'The ID of the task to which this branch is associated'
runs:
  using: 'node12'
  main: 'dist/index.js'
